{"name": "test_a", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <sample.test_demo1.TestClass object at 0x000001AFBA165748>\n\n    @pytest.mark.b\n    def test_a(self):\n>       assert 1 == 2\nE       assert 1 == 2\n\nsample\\test_demo1.py:14: AssertionError"}, "start": 1585459398336, "stop": 1585459398336, "uuid": "be14eecb-e703-4245-8326-d7f53b6b9566", "historyId": "6f708fcb54d78b8cafa40f4b1a15fad4", "testCaseId": "942a6da56485752ad5f7234d88c917fc", "fullName": "sample.test_demo1.TestClass#test_a", "labels": [{"name": "tag", "value": "b"}, {"name": "parentSuite", "value": "sample"}, {"name": "suite", "value": "test_demo1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-3BKS4R6"}, {"name": "thread", "value": "9828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "sample.test_demo1"}]}